[tool.poetry]
name = "grimoire-elk-gitee"
version = "0.103.0-rc.2"
description = "GrimoireELK processes and stores software development data to ElasticSearch"
readme = "README.md"
authors = [
    "Yehui Wang, Willem Jiang, Chenqi Shan"
]
repository = "https://github.com/chaoss/grimoirelab-elk-gitee"
keywords = ["development repositories analytics"]
license = "GPL-3.0-or-later"
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8'
]

packages = [
   { include = "grimoire_elk_gitee"},
   { include = "tests", format = "sdist" },
]

include = [
  "grimoire_elk_gitee/enriched/mappings/*.json"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/chaoss/grimoirelab-elk-gitee/issues"

[tool.poetry.scripts]
p2o = 'utils.p2o:main'
gelk_mapping = 'utils.gelk_mapping:main'

[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "6.3.1"
elasticsearch-dsl = "6.3.1"
requests = "2.26.0"
urllib3 = "1.26.5"
geopy = "^2.0.0"
PyMySQL = "0.9.3"
pandas = ">=0.22.0,<=0.25.3"
statsmodels = ">=0.9.0"
sortinghat = { version = ">=0.7.20", allow-prereleases = true}
grimoirelab-toolkit = { version = ">=0.3", allow-prereleases = true}
cereslib = { version = ">=0.3", allow-prereleases = true}
graal = { version = ">=0.3", allow-prereleases = true}
perceval = { version = ">=0.19", allow-prereleases = true }
perceval-mozilla = { version = ">=0.3", allow-prereleases = true}
perceval-opnfv = { version = ">=0.2", allow-prereleases = true}
perceval-puppet = { version = ">=0.2", allow-prereleases = true}
perceval-weblate = { version = ">=0.2", allow-prereleases = true}

[tool.poetry.dev-dependencies]
httpretty = "^0.9.6"
flake8 = "^3.9.2"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"